/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness
         * @description Is the process alive? Never touches a dependency.
         */
        get: operations["liveness_healthz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness
         * @description Can this replica serve traffic? Checked by the deploy gate.
         */
        get: operations["readiness_readyz_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Password Grant
         * @description OAuth2-style password grant.
         *
         *     Security notes: the login bucket is far tighter than the global one; a
         *     failure for an unknown email costs the same CPU as one for a known email
         *     (`dummy_verify`); and the error message is identical in every failure case
         *     so the endpoint cannot be used to enumerate accounts.
         */
        post: operations["password_grant_v1_auth_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/client-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Client Credentials
         * @description Machine principals: the batch loader and the ML service.
         *
         *     In production this sits behind mTLS as well; the shared secret alone is not
         *     the whole control.
         */
        post: operations["client_credentials_v1_auth_client_token_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh Token
         * @description Rotating refresh with family reuse detection.
         *
         *     Presenting an already-used token is the signature of a stolen credential
         *     being replayed, so the entire family is revoked and the legitimate user is
         *     forced to log in again.
         */
        post: operations["refresh_token_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Revokes the presented access token by jti and kills the refresh family.
         */
        post: operations["logout_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Transactions
         * @description Keyset-paginated transaction list — flagged and clean together.
         *
         *     `has_alert` is the fraud / non-fraud switch. Omitting it returns both, which
         *     is the honest default: a view built only from alerts shows the 1% that got
         *     flagged and hides the 99% that did not.
         *
         *     Served from the read replica, ordered by (booked_at, id), cursor-paged. No
         *     OFFSET anywhere, so a deep page costs what the first page costs.
         */
        get: operations["list_transactions_v1_transactions_get"];
        put?: never;
        /**
         * Create Transaction
         * @description Ingest one transaction and return its fraud verdict.
         *
         *     201 -> stored and scored. 202 -> stored, scoring PENDING (model was slow or
         *     down); the score arrives via the worker and is readable at
         *     GET /v1/transactions/{id}/score.
         */
        post: operations["create_transaction_v1_transactions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{transaction_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Transaction */
        get: operations["get_transaction_v1_transactions__transaction_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/transactions/{transaction_id}/score": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Transaction Score
         * @description Latest verdict for a transaction. This is what a client polls after a 202.
         */
        get: operations["get_transaction_score_v1_transactions__transaction_id__score_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/scores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Push Score */
        post: operations["push_score_v1_scores_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fraud-alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Alerts
         * @description Keyset-paginated alert queue, served from the read replica.
         */
        get: operations["list_alerts_v1_fraud_alerts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/fraud-alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Alert */
        get: operations["get_alert_v1_fraud_alerts__alert_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Patch Alert
         * @description Triage an alert. Transitions are validated against a state machine, and
         *     closing an alert needs a stronger scope than merely commenting on it.
         */
        patch: operations["patch_alert_v1_fraud_alerts__alert_id__patch"];
        trace?: never;
    };
    "/v1/cases": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Cases */
        get: operations["list_cases_v1_cases_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Case */
        get: operations["get_case_v1_cases__case_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Case */
        patch: operations["patch_case_v1_cases__case_id__patch"];
        trace?: never;
    };
    "/v1/cases/{case_id}/alerts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Alert To Case
         * @description Attach an alert the grouping rule missed.
         */
        post: operations["add_alert_to_case_v1_cases__case_id__alerts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/cases/{case_id}/alerts/{alert_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Alert From Case
         * @description Detach an alert the analyst judges unrelated to this scheme.
         */
        delete: operations["remove_alert_from_case_v1_cases__case_id__alerts__alert_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Entities */
        get: operations["list_entities_v1_entities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{party_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Entity */
        get: operations["get_entity_v1_entities__party_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/entities/{party_id}/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Entity Transactions */
        get: operations["entity_transactions_v1_entities__party_id__transactions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/network/accounts/{account_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Account Graph */
        get: operations["account_graph_v1_network_accounts__account_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/network/entities/{party_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Entity Graph
         * @description Graph centred on a party, expanded from its first held account.
         *
         *     A party with several accounts is entered through one of them; the rest
         *     appear as neighbours once the expansion reaches the transactions that
         *     connect them, which is the honest rendering -- accounts a party holds but
         *     never moved money between are not edges, and drawing them as such would
         *     invent a relationship the ledger does not show.
         */
        get: operations["entity_graph_v1_network_entities__party_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/audit-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Audit Logs
         * @description Newest-first trail. Filter by entity, entity_id, action, actor or date.
         *
         *     `entity=fraud_case&entity_id=<id>` is the case-history view: every action
         *     taken against one investigation, in order.
         */
        get: operations["list_audit_logs_v1_audit_logs_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_v1_users_get"];
        put?: never;
        /**
         * Create User
         * @description Password strength is enforced by the schema; the hash never leaves this layer.
         */
        post: operations["create_user_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{user_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Deactivate User
         * @description Takes effect within PRINCIPAL_CACHE_SECONDS, not at token expiry: the
         *     cached principal entry is dropped here so live tokens stop working.
         */
        post: operations["deactivate_user_v1_users__user_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/metrics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Overview
         * @description Counts, distributions and a time series for the requested window.
         *
         *     Everything is aggregated in SQL and returned already reduced — the caller
         *     receives a few dozen numbers, never a page of rows to add up itself.
         *
         *     Scoped to the caller's team unless they hold cross-team visibility, using
         *     the same rule as the alert queue.
         */
        get: operations["overview_v1_metrics_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/feedback/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Feedback
         * @description Closed cases with their investigator verdict, oldest first.
         *
         *     Ordered ascending by decision time so a training job can pull
         *     incrementally: keep the last `next_cursor`, pass it back next run, receive
         *     only what has been decided since. Newest-first would force a full walk to
         *     the end of history to find new rows.
         *
         *     Every score field here is the value recorded **at the moment the human
         *     decided**, not a re-read of the current model's opinion. See CaseFeedback.
         */
        get: operations["export_feedback_v1_feedback_export_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AccountIn */
        AccountIn: {
            /** Iban */
            iban: string;
            /** Institution Bic */
            institution_bic?: string | null;
            /** Currency */
            currency: string;
            /** Opened On */
            opened_on?: string | null;
            holder: components["schemas"]["PartyIn"];
        };
        /** AlertDetailOut */
        AlertDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transaction Id
             * Format: uuid
             */
            transaction_id: string;
            /** Score Id */
            score_id?: string | null;
            /** Case Id */
            case_id?: string | null;
            /** Status */
            status: string;
            /** Severity */
            severity: string;
            /** Risk Score */
            risk_score?: number | null;
            /** Team */
            team: string;
            /** Assigned To */
            assigned_to: string | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Amount */
            amount?: string | null;
            /** Currency */
            currency?: string | null;
            provenance?: components["schemas"]["AlertProvenanceOut"] | null;
            /** Events */
            events?: components["schemas"]["AlertEventOut"][];
            /** Explanation */
            explanation?: {
                [key: string]: unknown;
            }[];
            /** Model Name */
            model_name?: string | null;
            /** Model Version */
            model_version?: string | null;
            /** Model Decision */
            model_decision?: string | null;
            /** Risk Engine Version */
            risk_engine_version?: string | null;
            /** Signals */
            signals?: {
                [key: string]: unknown;
            } | null;
            /** Triggered Rules */
            triggered_rules?: {
                [key: string]: unknown;
            }[];
            /** Network */
            network?: {
                [key: string]: unknown;
            } | null;
            /** Anomaly */
            anomaly?: {
                [key: string]: unknown;
            } | null;
            /** Decision Reasons */
            decision_reasons?: {
                [key: string]: unknown;
            }[];
            feedback?: components["schemas"]["FeedbackOut"] | null;
        };
        /** AlertEventOut */
        AlertEventOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** From Status */
            from_status: string | null;
            /** To Status */
            to_status: string;
            /** Note */
            note: string | null;
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /** AlertOut */
        AlertOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transaction Id
             * Format: uuid
             */
            transaction_id: string;
            /** Score Id */
            score_id?: string | null;
            /** Case Id */
            case_id?: string | null;
            /** Status */
            status: string;
            /** Severity */
            severity: string;
            /** Risk Score */
            risk_score?: number | null;
            /** Team */
            team: string;
            /** Assigned To */
            assigned_to: string | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Closed At */
            closed_at: string | null;
            /** Amount */
            amount?: string | null;
            /** Currency */
            currency?: string | null;
            provenance?: components["schemas"]["AlertProvenanceOut"] | null;
        };
        /** AlertPatch */
        AlertPatch: {
            status?: components["schemas"]["AlertStatus"] | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Note */
            note?: string | null;
        };
        /**
         * AlertProvenanceOut
         * @description The exact score that opened this alert. Immutable for the life of the case.
         */
        AlertProvenanceOut: {
            /**
             * Transaction Id
             * Format: uuid
             */
            transaction_id: string;
            /** Score Id */
            score_id?: string | null;
            /**
             * Alert Id
             * Format: uuid
             */
            alert_id: string;
            /** Model Name */
            model_name?: string | null;
            /** Model Version */
            model_version?: string | null;
            /** Risk Engine Version */
            risk_engine_version?: string | null;
            /** Scored At */
            scored_at?: string | null;
        };
        /** AlertRefOut */
        AlertRefOut: {
            /**
             * Alert Id
             * Format: uuid
             */
            alert_id: string;
            /** Status */
            status: string;
            /** Severity */
            severity: string;
        };
        /**
         * AlertSeverity
         * @enum {string}
         */
        AlertSeverity: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
        /**
         * AlertStatus
         * @enum {string}
         */
        AlertStatus: "OPEN" | "IN_REVIEW" | "ESCALATED" | "CONFIRMED_FRAUD" | "FALSE_POSITIVE" | "CLOSED";
        /** AuditEntryOut */
        AuditEntryOut: {
            /** Id */
            id: number;
            /** Actor */
            actor: string;
            /** Actor Type */
            actor_type: string;
            /** Action */
            action: string;
            /** Entity */
            entity: string;
            /** Entity Id */
            entity_id?: string | null;
            /** Request Id */
            request_id?: string | null;
            /** Ip */
            ip?: string | null;
            /** Detail */
            detail?: {
                [key: string]: unknown;
            } | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
        };
        /**
         * CaseAlertOut
         * @description One alert inside a case. Deliberately thin -- the case list must not
         *     turn into N full alert payloads.
         */
        CaseAlertOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Transaction Id
             * Format: uuid
             */
            transaction_id: string;
            /** Score Id */
            score_id?: string | null;
            /** Status */
            status: string;
            /** Severity */
            severity: string;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
        };
        /** CaseAlertRef */
        CaseAlertRef: {
            /**
             * Alert Id
             * Format: uuid
             */
            alert_id: string;
        };
        /** CaseDetailOut */
        CaseDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Severity */
            severity: string;
            /** Team */
            team: string;
            /** Assigned To */
            assigned_to?: string | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Closed At */
            closed_at?: string | null;
            /**
             * Alert Count
             * @default 0
             */
            alert_count: number;
            /** Alerts */
            alerts?: components["schemas"]["CaseAlertOut"][];
            feedback?: components["schemas"]["FeedbackOut"] | null;
        };
        /** CaseOut */
        CaseOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Title */
            title: string;
            /** Status */
            status: string;
            /** Severity */
            severity: string;
            /** Team */
            team: string;
            /** Assigned To */
            assigned_to?: string | null;
            /**
             * Opened At
             * Format: date-time
             */
            opened_at: string;
            /** Closed At */
            closed_at?: string | null;
            /**
             * Alert Count
             * @default 0
             */
            alert_count: number;
        };
        /** CasePatch */
        CasePatch: {
            status?: components["schemas"]["AlertStatus"] | null;
            /** Title */
            title?: string | null;
            /** Assigned To */
            assigned_to?: string | null;
            /** Note */
            note?: string | null;
            feedback?: components["schemas"]["FeedbackIn"] | null;
        };
        /** ClientCredentialsRequest */
        ClientCredentialsRequest: {
            /** Client Id */
            client_id: string;
            /** Client Secret */
            client_secret: string;
        };
        /** EntityAccountOut */
        EntityAccountOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Account Last4 */
            account_last4: string;
            /** Currency */
            currency: string;
            /** Country Code */
            country_code: string;
            /** Status */
            status: string;
            /** Holder Role */
            holder_role: string;
            /** Opened On */
            opened_on?: string | null;
        };
        /** EntityDetailOut */
        EntityDetailOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Party Type */
            party_type: string;
            /** Display Name */
            display_name: string;
            /** Country Code */
            country_code: string;
            /** External Ref */
            external_ref?: string | null;
            /** Risk Tier */
            risk_tier: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Account Count
             * @default 0
             */
            account_count: number;
            /**
             * Transaction Count
             * @default 0
             */
            transaction_count: number;
            /** Pep Flag */
            pep_flag?: boolean | null;
            /** Registration No */
            registration_no?: string | null;
            /** Legal Form */
            legal_form?: string | null;
            /** Sector Code */
            sector_code?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /**
             * Accounts
             * @default []
             */
            accounts: components["schemas"]["EntityAccountOut"][];
        };
        /**
         * EntityOut
         * @description List row. Cheap enough to render a table of 50 without a second query.
         */
        EntityOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Party Type */
            party_type: string;
            /** Display Name */
            display_name: string;
            /** Country Code */
            country_code: string;
            /** External Ref */
            external_ref?: string | null;
            /** Risk Tier */
            risk_tier: number;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Account Count
             * @default 0
             */
            account_count: number;
            /**
             * Transaction Count
             * @default 0
             */
            transaction_count: number;
            /** Pep Flag */
            pep_flag?: boolean | null;
            /** Registration No */
            registration_no?: string | null;
            /** Legal Form */
            legal_form?: string | null;
            /** Sector Code */
            sector_code?: string | null;
        };
        /**
         * EntityTransactionOut
         * @description A movement seen from one party's point of view.
         *
         *     `direction` is relative to the entity being viewed, not to the transaction:
         *     the same row is OUT for the sender and IN for the receiver. INTERNAL means
         *     the party holds both sides, which is the shape a layering step takes.
         */
        EntityTransactionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** External Ref */
            external_ref?: string | null;
            /** Direction */
            direction: string;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /**
             * Booked At
             * Format: date-time
             */
            booked_at: string;
            /** Transaction Type */
            transaction_type: string;
            /** Scoring Status */
            scoring_status: string;
            /**
             * Counterparty Account Id
             * Format: uuid
             */
            counterparty_account_id: string;
            /**
             * Src Account Id
             * Format: uuid
             */
            src_account_id: string;
            /**
             * Dst Account Id
             * Format: uuid
             */
            dst_account_id: string;
        };
        /**
         * FeedbackExportItem
         * @description One row of the retraining export.
         *
         *     Same shape as the read model plus the transaction's own identifiers, so a
         *     training pipeline can join back to features without a second API call.
         *     `team` is included because a model trained on one jurisdiction's verdicts
         *     should be able to say so.
         */
        FeedbackExportItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Anchor Alert Id */
            anchor_alert_id?: string | null;
            /** Score Id */
            score_id?: string | null;
            /** Transaction Id */
            transaction_id?: string | null;
            /**
             * Alert Count
             * @default 1
             */
            alert_count: number;
            final_label: components["schemas"]["FinalLabel"];
            confidence: components["schemas"]["LabelConfidence"];
            model_agreement: components["schemas"]["ModelAgreement"];
            /** Fraud Typology */
            fraud_typology?: string | null;
            /** Decision Drivers */
            decision_drivers?: string[];
            /** Missing Signals */
            missing_signals?: string[];
            /** Notes */
            notes?: string | null;
            /** Reviewer User Id */
            reviewer_user_id?: string | null;
            /** Alert Opened At */
            alert_opened_at?: string | null;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Model Version */
            model_version?: string | null;
            /** Risk Engine Version */
            risk_engine_version?: string | null;
            /** Original Risk Score */
            original_risk_score?: number | null;
            /** Original Model Score */
            original_model_score?: number | null;
            /** Original Rule Score */
            original_rule_score?: number | null;
            /** Original Anomaly Score */
            original_anomaly_score?: number | null;
            /** Original Network Score */
            original_network_score?: number | null;
            /** Original Triggered Rules */
            original_triggered_rules?: unknown[];
            /** External Ref */
            external_ref?: string | null;
            /** Team */
            team: string;
        };
        /**
         * FeedbackIn
         * @description What the investigator supplies when closing a case.
         */
        FeedbackIn: {
            final_label: components["schemas"]["FinalLabel"];
            confidence: components["schemas"]["LabelConfidence"];
            model_agreement: components["schemas"]["ModelAgreement"];
            /** Fraud Typology */
            fraud_typology?: string | null;
            /** Decision Drivers */
            decision_drivers?: string[];
            /** Missing Signals */
            missing_signals?: string[];
            /** Notes */
            notes?: string | null;
        };
        /**
         * FeedbackOut
         * @description Read-back on the case page.
         */
        FeedbackOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Case Id
             * Format: uuid
             */
            case_id: string;
            /** Anchor Alert Id */
            anchor_alert_id?: string | null;
            /** Score Id */
            score_id?: string | null;
            /** Transaction Id */
            transaction_id?: string | null;
            /**
             * Alert Count
             * @default 1
             */
            alert_count: number;
            final_label: components["schemas"]["FinalLabel"];
            confidence: components["schemas"]["LabelConfidence"];
            model_agreement: components["schemas"]["ModelAgreement"];
            /** Fraud Typology */
            fraud_typology?: string | null;
            /** Decision Drivers */
            decision_drivers?: string[];
            /** Missing Signals */
            missing_signals?: string[];
            /** Notes */
            notes?: string | null;
            /** Reviewer User Id */
            reviewer_user_id?: string | null;
            /** Alert Opened At */
            alert_opened_at?: string | null;
            /**
             * Decided At
             * Format: date-time
             */
            decided_at: string;
            /** Model Version */
            model_version?: string | null;
            /** Risk Engine Version */
            risk_engine_version?: string | null;
            /** Original Risk Score */
            original_risk_score?: number | null;
            /** Original Model Score */
            original_model_score?: number | null;
            /** Original Rule Score */
            original_rule_score?: number | null;
            /** Original Anomaly Score */
            original_anomaly_score?: number | null;
            /** Original Network Score */
            original_network_score?: number | null;
            /** Original Triggered Rules */
            original_triggered_rules?: unknown[];
        };
        /**
         * FinalLabel
         * @description The investigator's verdict. Deliberately separate from AlertStatus.
         *
         *     A closed alert is a workflow fact; a label is an evidential one. Keeping
         *     them apart means INCONCLUSIVE is expressible -- a case can be closed
         *     without becoming a training example, which is exactly what you want when
         *     the analyst genuinely could not tell.
         * @enum {string}
         */
        FinalLabel: "CONFIRMED_FRAUD" | "FALSE_POSITIVE" | "INCONCLUSIVE";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Checks */
            checks?: {
                [key: string]: string;
            };
        };
        /**
         * LabelConfidence
         * @enum {string}
         */
        LabelConfidence: "LOW" | "MEDIUM" | "HIGH";
        /**
         * ModelAgreement
         * @description Did the investigator's conclusion match what the engine said?
         *
         *     Recorded explicitly rather than derived, because deriving it would bake in
         *     today's threshold. An AGREES row stays true even after the threshold moves.
         * @enum {string}
         */
        ModelAgreement: "AGREES" | "DISAGREES" | "PARTIAL";
        /** NetworkEdgeOut */
        NetworkEdgeOut: {
            /** Source */
            source: string;
            /** Target */
            target: string;
            /** Transaction Count */
            transaction_count: number;
            /** Total Amount */
            total_amount: string;
            /** Currency */
            currency?: string | null;
            /** Last Booked At */
            last_booked_at?: string | null;
        };
        /** NetworkGraphOut */
        NetworkGraphOut: {
            /** Focus Account Id */
            focus_account_id: string;
            /** Depth */
            depth: number;
            /** Window Days */
            window_days: number;
            /** Nodes */
            nodes: components["schemas"]["NetworkNodeOut"][];
            /** Edges */
            edges: components["schemas"]["NetworkEdgeOut"][];
            /** Truncated */
            truncated: boolean;
        };
        /** NetworkNodeOut */
        NetworkNodeOut: {
            /** Id */
            id: string;
            /** Label */
            label?: string | null;
            /** Account Last4 */
            account_last4?: string | null;
            /** Currency */
            currency?: string | null;
            /** Country Code */
            country_code?: string | null;
            /** Status */
            status?: string | null;
            /** Hop */
            hop: number;
            /** Is Focus */
            is_focus: boolean;
            /** Alert Count */
            alert_count: number;
        };
        /** Page[AlertOut] */
        Page_AlertOut_: {
            /** Items */
            items: components["schemas"]["AlertOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Page Size */
            page_size: number;
        };
        /** Page[AuditEntryOut] */
        Page_AuditEntryOut_: {
            /** Items */
            items: components["schemas"]["AuditEntryOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Page Size */
            page_size: number;
        };
        /** Page[CaseOut] */
        Page_CaseOut_: {
            /** Items */
            items: components["schemas"]["CaseOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Page Size */
            page_size: number;
        };
        /** Page[EntityOut] */
        Page_EntityOut_: {
            /** Items */
            items: components["schemas"]["EntityOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Page Size */
            page_size: number;
        };
        /** Page[EntityTransactionOut] */
        Page_EntityTransactionOut_: {
            /** Items */
            items: components["schemas"]["EntityTransactionOut"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Page Size */
            page_size: number;
        };
        /** Page[FeedbackExportItem] */
        Page_FeedbackExportItem_: {
            /** Items */
            items: components["schemas"]["FeedbackExportItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Page Size */
            page_size: number;
        };
        /** Page[TransactionListItem] */
        Page_TransactionListItem_: {
            /** Items */
            items: components["schemas"]["TransactionListItem"][];
            /** Next Cursor */
            next_cursor?: string | null;
            /** Page Size */
            page_size: number;
        };
        /** PartyIn */
        PartyIn: {
            /**
             * Party Type
             * @enum {string}
             */
            party_type: "PERSON" | "COMPANY";
            /** Display Name */
            display_name: string;
            /** Country Code */
            country_code: string;
            /** External Ref */
            external_ref?: string | null;
            /**
             * Risk Tier
             * @default 1
             */
            risk_tier: number;
            /** National Id */
            national_id?: string | null;
            /** Date Of Birth */
            date_of_birth?: string | null;
            /**
             * Pep Flag
             * @default false
             */
            pep_flag: boolean;
            /** Registration No */
            registration_no?: string | null;
            /** Legal Form */
            legal_form?: string | null;
            /** Sector Code */
            sector_code?: string | null;
        };
        /**
         * PartyType
         * @enum {string}
         */
        PartyType: "PERSON" | "COMPANY";
        /** ReasonOut */
        ReasonOut: {
            /** Feature */
            feature: string;
            /** Contribution */
            contribution: number;
            /** Direction */
            direction?: ("FRAUD" | "LEGITIMATE") | null;
            /** Description */
            description?: string | null;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * RiskLevel
         * @enum {string}
         */
        RiskLevel: "LOW" | "MEDIUM" | "HIGH";
        /** RiskOut */
        RiskOut: {
            /** Risk Level */
            risk_level: string;
            /** Model Name */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Explanation */
            explanation?: components["schemas"]["ReasonOut"][];
            /** Model Decision */
            model_decision?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /** Scored At */
            scored_at?: string | null;
            /** Risk Score */
            risk_score?: number | null;
            /** Risk Engine Version */
            risk_engine_version?: string | null;
            signals?: components["schemas"]["SignalScoresOut"] | null;
            /** Anomaly */
            anomaly?: {
                [key: string]: unknown;
            } | null;
            /** Network */
            network?: {
                [key: string]: unknown;
            } | null;
            /** Triggered Rules */
            triggered_rules?: components["schemas"]["TriggeredRuleOut"][];
            /** Decision Reasons */
            decision_reasons?: {
                [key: string]: unknown;
            }[];
        };
        /**
         * ScorePush
         * @description Body of POST /v1/scores — the ML service's push path.
         *
         *     Mirrors the pull response, so a model that works in one direction works in
         *     the other. `risk_level` and `decision` are accepted but advisory: both are
         *     recomputed from our own thresholds.
         */
        ScorePush: {
            /**
             * Transaction Id
             * Format: uuid
             */
            transaction_id: string;
            /** Fraud Probability */
            fraud_probability: number;
            /** Risk Level */
            risk_level?: ("LOW" | "MEDIUM" | "HIGH") | null;
            /** Decision */
            decision?: ("ALLOW" | "REVIEW" | "BLOCK") | null;
            /** Explanation */
            explanation?: {
                [key: string]: unknown;
            }[];
            /**
             * Model Name
             * @default fraud-model
             */
            model_name: string;
            /** Model Version */
            model_version: string;
            /** Latency Ms */
            latency_ms?: number | null;
        };
        /** ScorePushResult */
        ScorePushResult: {
            /**
             * Score Id
             * Format: uuid
             */
            score_id: string;
            /**
             * Transaction Id
             * Format: uuid
             */
            transaction_id: string;
            /** Risk Level */
            risk_level: string;
            /** Alert */
            alert?: {
                [key: string]: unknown;
            } | null;
            /** Created */
            created: boolean;
        };
        /**
         * ScoringStatus
         * @enum {string}
         */
        ScoringStatus: "COMPLETE" | "PENDING" | "FAILED";
        /**
         * SignalScoresOut
         * @description The four signals behind the verdict, before blending. Scale is 0-100.
         */
        SignalScoresOut: {
            /** Model Score */
            model_score: number;
            /** Rule Score */
            rule_score: number;
            /** Anomaly Score */
            anomaly_score: number;
            /** Network Score */
            network_score: number;
            /** Weighted Score */
            weighted_score: number;
            /**
             * Rule Floor Applied
             * @default false
             */
            rule_floor_applied: boolean;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
            /** Expires In */
            expires_in: number;
            /** Scopes */
            scopes: string[];
        };
        /** TransactionCreate */
        TransactionCreate: {
            /** External Ref */
            external_ref?: string | null;
            /** Amount */
            amount: number | string;
            /** Currency */
            currency: string;
            /**
             * Booked At
             * Format: date-time
             */
            booked_at: string;
            transaction_type: components["schemas"]["TransactionType"];
            /** Mcc */
            mcc?: number | null;
            /** Sender Balance Before */
            sender_balance_before: number | string;
            /** Receiver Balance Before */
            receiver_balance_before: number | string;
            source_account: components["schemas"]["AccountIn"];
            destination_account: components["schemas"]["AccountIn"];
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        /** TransactionCreated */
        TransactionCreated: {
            /**
             * Transaction Id
             * Format: uuid
             */
            transaction_id: string;
            /**
             * Scoring
             * @enum {string}
             */
            scoring: "COMPLETE" | "PENDING" | "FAILED";
            risk?: components["schemas"]["RiskOut"] | null;
            alert?: components["schemas"]["AlertRefOut"] | null;
            /** Links */
            links?: {
                [key: string]: string;
            };
        };
        /**
         * TransactionListItem
         * @description One row of the transaction list.
         *
         *     Risk and alert fields are flattened onto the row deliberately: the caller is
         *     rendering a table, and making it fetch a score per row would be an N+1 that
         *     turns one page into a hundred requests.
         */
        TransactionListItem: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** External Ref */
            external_ref: string | null;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /**
             * Booked At
             * Format: date-time
             */
            booked_at: string;
            /** Transaction Type */
            transaction_type: string;
            /** Scoring Status */
            scoring_status: string;
            /** Team */
            team: string | null;
            /** Src Account Last4 */
            src_account_last4: string;
            /** Dst Account Last4 */
            dst_account_last4: string;
            /**
             * Src Account Id
             * Format: uuid
             */
            src_account_id: string;
            /**
             * Dst Account Id
             * Format: uuid
             */
            dst_account_id: string;
            /** Risk Score */
            risk_score?: number | null;
            /** Risk Level */
            risk_level?: string | null;
            /** Alert Id */
            alert_id?: string | null;
            /** Alert Status */
            alert_status?: string | null;
            /** Alert Severity */
            alert_severity?: string | null;
        };
        /** TransactionOut */
        TransactionOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** External Ref */
            external_ref: string | null;
            /** Amount */
            amount: string;
            /** Currency */
            currency: string;
            /**
             * Booked At
             * Format: date-time
             */
            booked_at: string;
            /** Transaction Type */
            transaction_type: string;
            /** Mcc */
            mcc: number | null;
            /** Sender Balance Before */
            sender_balance_before: string;
            /** Receiver Balance Before */
            receiver_balance_before: string;
            /** Scoring Status */
            scoring_status: string;
            /** Src Account Last4 */
            src_account_last4: string;
            /** Dst Account Last4 */
            dst_account_last4: string;
            /**
             * Src Account Id
             * Format: uuid
             */
            src_account_id: string;
            /**
             * Dst Account Id
             * Format: uuid
             */
            dst_account_id: string;
        };
        /**
         * TransactionType
         * @description PaySim's vocabulary, because that is what the model was trained on.
         * @enum {string}
         */
        TransactionType: "TRANSFER" | "CASH_OUT" | "CASH_IN" | "PAYMENT" | "DEBIT";
        /** TriggeredRuleOut */
        TriggeredRuleOut: {
            /** Rule */
            rule: string;
            /** Severity */
            severity: string;
            /** Description */
            description: string;
        };
        /** UserCreate */
        UserCreate: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name?: string | null;
            /** Password */
            password: string;
            /**
             * Team
             * @default default
             */
            team: string;
            /** Roles */
            roles?: string[];
        };
        /** UserOut */
        UserOut: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string | null;
            /** Team */
            team: string;
            /** Is Active */
            is_active: boolean;
            /** Scopes */
            scopes: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    liveness_healthz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_readyz_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    password_grant_v1_auth_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    client_credentials_v1_auth_client_token_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientCredentialsRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refresh_token_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    list_transactions_v1_transactions_get: {
        parameters: {
            query?: {
                risk_level?: components["schemas"]["RiskLevel"] | null;
                transaction_type?: components["schemas"]["TransactionType"] | null;
                scoring_status?: components["schemas"]["ScoringStatus"] | null;
                /** @description true = flagged, false = clean */
                has_alert?: boolean | null;
                min_probability?: number | null;
                max_probability?: number | null;
                booked_from?: string | null;
                booked_to?: string | null;
                min_amount?: number | string | null;
                max_amount?: number | string | null;
                /** @description external_ref prefix */
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_TransactionListItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_transaction_v1_transactions_post: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TransactionCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionCreated"];
                };
            };
            /** @description Stored; scoring deferred to the async worker */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Conflicting data */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_transaction_v1_transactions__transaction_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransactionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_transaction_score_v1_transactions__transaction_id__score_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                transaction_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RiskOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    push_score_v1_scores_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScorePush"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScorePushResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_alerts_v1_fraud_alerts_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["AlertStatus"] | null;
                severity?: components["schemas"]["AlertSeverity"] | null;
                min_probability?: number | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AlertOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_alert_v1_fraud_alerts__alert_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_alert_v1_fraud_alerts__alert_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AlertPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AlertDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_cases_v1_cases_get: {
        parameters: {
            query?: {
                status?: components["schemas"]["AlertStatus"] | null;
                severity?: components["schemas"]["AlertSeverity"] | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_CaseOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_case_v1_cases__case_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_case_v1_cases__case_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CasePatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_alert_to_case_v1_cases__case_id__alerts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CaseAlertRef"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_alert_from_case_v1_cases__case_id__alerts__alert_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                case_id: string;
                alert_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CaseDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_entities_v1_entities_get: {
        parameters: {
            query?: {
                party_type?: components["schemas"]["PartyType"] | null;
                country_code?: string | null;
                min_risk_tier?: number | null;
                q?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EntityOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_entity_v1_entities__party_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                party_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EntityDetailOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_transactions_v1_entities__party_id__transactions_get: {
        parameters: {
            query?: {
                direction?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                party_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_EntityTransactionOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    account_graph_v1_network_accounts__account_id__get: {
        parameters: {
            query?: {
                depth?: number;
                window_days?: number;
                max_nodes?: number;
            };
            header?: never;
            path: {
                account_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkGraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    entity_graph_v1_network_entities__party_id__get: {
        parameters: {
            query?: {
                depth?: number;
                window_days?: number;
                max_nodes?: number;
            };
            header?: never;
            path: {
                party_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NetworkGraphOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_audit_logs_v1_audit_logs_get: {
        parameters: {
            query?: {
                entity?: string | null;
                entity_id?: string | null;
                action?: string | null;
                actor?: string | null;
                created_from?: string | null;
                created_to?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_AuditEntryOut_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_v1_users_get: {
        parameters: {
            query?: {
                team?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_user_v1_users__user_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    overview_v1_metrics_overview_get: {
        parameters: {
            query?: {
                from?: string | null;
                to?: string | null;
                bucket?: "hour" | "day";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_feedback_v1_feedback_export_get: {
        parameters: {
            query?: {
                final_label?: components["schemas"]["FinalLabel"] | null;
                decided_from?: string | null;
                decided_to?: string | null;
                include_inconclusive?: boolean;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Page_FeedbackExportItem_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
